[tool.black]
line_length = 80

[tool.pyright]
typeCheckingMode = "basic"

reportIncompatibleMethodOverride = "error"
reportPrivateImportUsage = "information"
reportOptionalSubscript = "none"

pythonVersion = "3.10"
pythonPlatform = "Linux"
